FROM docker:24.0

# Install AWS CLI v2 and jq
RUN apk add --no-cache curl unzip bash jq \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf aws awscliv2.zip
